[tool.poetry]
name = "y"
version = "0.1.0"
description = ""
authors = ["Conrad Dean <conrad.p.dean@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
